== Quick Start

If you are itching to get started, here's what you need to do to get up and running.

=== Using `http-builder-ng` in Groovy scripts

An easy way to use `http-builder-ng` in a *Groovy* script is to import one of its client script flavours using https://groovy-lang.org/grape.html[Grape].

[source,groovy]
----
@Grab('io.github.http-builder-ng:http-builder-ng-core:1.0.4') // <1>
@Grab('org.jsoup:jsoup:1.13.1')

import static groovyx.net.http.HttpBuilder.configure
import org.jsoup.nodes.Document

Document page = configure { // <2>
    
    request.uri = 'http://www.apache.org/'
    request.headers['User-Agent'] = 'Apache-Groovy/3.0.2'

}.get()

println "Title of Apache main page: ${page.title()}"
----
<1> This example uses the `core` flavour.
<2> Under the hoods the response is parsed by jsoup library


=== Add Library to Project

First, you need the library in your project. If you are using Gradle, add the following dependency to your `build.gradle` file `dependencies` closure:

    compile 'io.github.http-builder-ng:http-builder-ng-CLIENT:1.0.4'

or, for Maven add the following to your `pom.xml` file:

    <dependency>
      <groupId>io.github.http-builder-ng</groupId>
      <artifactId>http-builder-ng-CLIENT</artifactId>
      <version>1.0.4</version>
    </dependency>

where `CLIENT` is replaced with the client library name (`core`, `apache`, or `okhttp`).

=== Instantiate `HttpBuilder`

Next, you need to instantiate an instance of `HttpBuilder` to make requests on. If you are using Groovy:

[source,groovy]
----
import static groovyx.net.http.HttpBuilder.configure

def http = configure {
    request.uri = 'http://localhost:9876'
}
----

or, if you are using Java:

[source,java]
----
import groovyx.net.http.HttpBuilder;
import static groovyx.net.http.HttpBuilder.configure;

HttpBuilder http = configure(config -> {
    config.getRequest().setUri("http://localhost:9876");
});
----

A `request.uri` is the only required property, though other global and client configurations may be configured in the `configure` block.

The code shown will use the default client library based on the Java `HttpUrlConnection`; however, you can also use the Apache HttpComponents or the
OkHttp client libraries. See the section on Client-Related Configuration for more details on switching client implementations.

=== Make Requests

Once you have the library and an instance of `HttpBuilder` you are ready to make requests. For Groovy:

[source,groovy]
----
String text = http.get(String){
    request.uri.path = '/name'
}
----

and for Java:

[source,java]
----
String text = http.get(String.class, cfg -> {
    cfg.getRequest().getUri().setPath("/name");
});
----

At the end of the User Guide there is an Examples section with some complete Groovy script examples.

== Common Usages

* If you want to deal with parsed content, do that in a link:#_status_handlers[`success`], link:#_status_handlers[`failure`], or
link:#_status_handlers[`when`] handler. This is probably what you want to do 99% of the time as a user of the library. Being able to easily consume
content as pre-parsed objects is one of the main selling points.
* If you want to deal with the data streams, do that by implementing a link:#_parsers[content parser]. You can use either the input stream or the
reader inside the `FromServer` interface (but not both). There is no need to worry about managing opening or closing the stream, the builders will do
the right thing. You are also free to duplicate or "tee" the stream or reader and delegate to existing parsers.
* If you want to do something out of band (such as logging or adding metrics), use an link:#_interceptors[`interceptor`] This is fairly easy to do
because neither what is requested nor what is returned is changed by the interceptor.
* If you want to change what is requested (before being sent) or change the object(s) returned from the content parser use an
link:#_interceptors[`interceptor`]. This is probably the most difficult to do because the order of interceptor invocation is not guaranteed but the
interceptor must still return to the user what is expected. If the user is expecting a `List` then the interceptor must make sure that the user gets that.
* If you want to handle unexpected exceptions, implement an link:#_exception_handlers[`exception`] handler.
